export { default as ArrowDown } from './ArrowDown'
export { default as ArrowRight } from './ArrowRight'
export { default as ChevronDown } from './ChevronDown'
export { default as WhatsApp } from './WhatsApp'
export { default as Phone } from './Phone'
export { default as Instagram } from './Instagram'
export { default as Plane } from './Plane'
export { default as Check } from './Check'
export { default as Cross } from './Cross'
export { default as CheckCircle } from './CheckCircle'
export { default as CrossCircle } from './CrossCircle'
export { default as MapPinOff } from './MapPinOff'
export type { IconProps } from './types'
